[package]
name = "rust-1brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-float = "0.2"
fxhash = "0.2.1"

[toolchain]
channel = "nightly"

[features]
slice_split_once = []